import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Footer, Sidebar } from '../widgets'
import { AppProvider } from '../entities'
import { LenisScrollProvider } from '../shared/components'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <LenisScrollProvider>
          <AppProvider>{children}</AppProvider>
          <Footer />
          <Sidebar />
        </LenisScrollProvider>
      </body>
    </html>
  )
}
